#
# This function will prevent in-source builds
function(AssureOutOfSourceBuilds)
  # make sure the user doesn't play dirty with symlinks
  get_filename_component(srcdir "${CMAKE_SOURCE_DIR}" REALPATH)
  get_filename_component(bindir "${CMAKE_BINARY_DIR}" REALPATH)

  # disallow in-source builds
  if("${srcdir}" STREQUAL "${bindir}")
    message("######################################################")
    message("# Should not be configured & built in the source directory")
    message("# You must run cmake in a build directory.")
    message("#")
    message("# For example:")
    message("# mkdir cxxstd-sandbox ; cd cxxstd-sandbox")
    message("# git clone https://bryan_flynt@bitbucket.org/bryan_flynt/cxxstd.git")
    message("# mkdir build")
    message("# this will create the following directory structure")
    message("#")
    message("# cxxstd-sandbox")
    message("#  +--cxxstd")
    message("#  +--build")
    message("#")
    message("# Then you can proceed to configure and build")
    message("# by using the following commands")
    message("#")
    message("# cd build")
    message("# cmake ../cxxstd  # or ccmake, or cmake-gui ")
    message("# make")
    message("#")
    message("# NOTE: Given that you already tried to make an in-source build")
    message("#       CMake have already created several files & directories")
    message("#       in your source tree. run 'git status' to find them and")
    message("#       remove them by doing:")
    message("#")
    message("#       cd cxxstd-sandbox/cxxstd")
    message("#       git clean -n -d")
    message("#       git clean -f -d")
    message("#       git checkout --")
    message("#")
    message("######################################################")
    message(FATAL_ERROR "Quitting configuration")
  endif()
endfunction()

AssureOutOfSourceBuilds()

